CREATE TABLE `simple_box_page` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `boxId` INTEGER NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `bundleImageUrl` VARCHAR(500) NULL,
  `bundleImageData` MEDIUMBLOB NULL,
  `bundleImageMimeType` VARCHAR(100) NULL,
  `bundleImageFileName` VARCHAR(255) NULL,
  `bannerImageUrl` VARCHAR(500) NULL,
  `bannerImageData` MEDIUMBLOB NULL,
  `bannerImageMimeType` VARCHAR(100) NULL,
  `bannerImageFileName` VARCHAR(255) NULL,
  `stepTitle` VARCHAR(255) NOT NULL DEFAULT 'Choose your products',
  `stepDescription` TEXT NULL,
  `productItems` INTEGER NOT NULL DEFAULT 3,
  `buttonLabel` VARCHAR(100) NOT NULL DEFAULT 'Add bundle to cart',
  `bundlePriceType` VARCHAR(10) NOT NULL DEFAULT 'dynamic',
  `discountMode` VARCHAR(30) NOT NULL DEFAULT 'fixed_amount',
  `discountType` VARCHAR(30) NOT NULL DEFAULT 'fixed',
  `discountValue` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `buyQuantity` INTEGER NOT NULL DEFAULT 1,
  `getQuantity` INTEGER NOT NULL DEFAULT 1,
  `selectedGiftProductIdsJson` LONGTEXT NULL,
  `productConfiguration` VARCHAR(40) NOT NULL DEFAULT 'whole_store',
  `selectedProductIdsJson` LONGTEXT NULL,
  `selectedCollectionIdsJson` LONGTEXT NULL,
  `scheduleType` VARCHAR(20) NOT NULL DEFAULT 'immediately',
  `startDate` VARCHAR(10) NULL,
  `startTime` VARCHAR(5) NULL,
  `hasEndDate` BOOLEAN NOT NULL DEFAULT false,
  `endDate` VARCHAR(10) NULL,
  `endTime` VARCHAR(5) NULL,
  `eligibilityJson` LONGTEXT NULL,
  `customerTags` TEXT NULL,
  `customers` TEXT NULL,
  `hideOutOfStockProducts` BOOLEAN NOT NULL DEFAULT false,
  `showProductSearch` BOOLEAN NOT NULL DEFAULT false,
  `hideBundleHeader` BOOLEAN NOT NULL DEFAULT false,
  `hideBannerImage` BOOLEAN NOT NULL DEFAULT false,
  `hideProductInfoModal` BOOLEAN NOT NULL DEFAULT false,
  `productImageAutoHeight` BOOLEAN NOT NULL DEFAULT false,
  `displayCompareAtPrice` BOOLEAN NOT NULL DEFAULT false,
  `redirectToCheckout` BOOLEAN NOT NULL DEFAULT false,
  `redirectToCart` BOOLEAN NOT NULL DEFAULT false,
  `backgroundColor` VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
  `cardBorderColor` VARCHAR(20) NOT NULL DEFAULT '#F2F2F2',
  `imageHeight` INTEGER NOT NULL DEFAULT 200,
  `imageHeightMobile` INTEGER NOT NULL DEFAULT 160,
  `imageDisplay` VARCHAR(30) NOT NULL DEFAULT 'Desktop/Mobile',
  `productCardDesktopSize` VARCHAR(20) NOT NULL DEFAULT 'Large',
  `productCardMobileSize` VARCHAR(20) NOT NULL DEFAULT 'Medium',
  `borderWidth` INTEGER NOT NULL DEFAULT 0,
  `borderRadius` INTEGER NOT NULL DEFAULT 0,
  `titleTextColor` VARCHAR(20) NOT NULL DEFAULT '#050505',
  `titleSize` INTEGER NOT NULL DEFAULT 14,
  `titleStyle` VARCHAR(20) NOT NULL DEFAULT 'Regular',
  `productPriceColor` VARCHAR(20) NOT NULL DEFAULT '#000000',
  `productPriceSize` INTEGER NOT NULL DEFAULT 14,
  `productPriceStyle` VARCHAR(20) NOT NULL DEFAULT 'Medium',
  `compareAtPriceColor` VARCHAR(20) NOT NULL DEFAULT '#9D9D9D',
  `compareAtPriceSize` INTEGER NOT NULL DEFAULT 12,
  `compareAtPriceStyle` VARCHAR(20) NOT NULL DEFAULT 'Light',
  `ctaBackgroundColor` VARCHAR(20) NOT NULL DEFAULT '#303030',
  `ctaTextColor` VARCHAR(20) NOT NULL DEFAULT '#F5F5F5',
  `ctaSize` INTEGER NOT NULL DEFAULT 14,
  `ctaStyle` VARCHAR(20) NOT NULL DEFAULT 'Bold',
  `variantSelectorColor` VARCHAR(20) NOT NULL DEFAULT '#383838',
  `variantSelectorSize` INTEGER NOT NULL DEFAULT 12,
  `variantSelectorStyle` VARCHAR(20) NOT NULL DEFAULT 'Regular',
  `imagePopupBackgroundColor` VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
  `imagePopupTextColor` VARCHAR(20) NOT NULL DEFAULT '#303030',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `simple_box_page_boxId_key` (`boxId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `simple_box_page_boxId_fkey`
    FOREIGN KEY (`boxId`) REFERENCES `combo_box` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `multiple_box_page` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `boxId` INTEGER NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `bundleImageUrl` VARCHAR(500) NULL,
  `bundleImageData` MEDIUMBLOB NULL,
  `bundleImageMimeType` VARCHAR(100) NULL,
  `bundleImageFileName` VARCHAR(255) NULL,
  `bannerImageUrl` VARCHAR(500) NULL,
  `bannerImageData` MEDIUMBLOB NULL,
  `bannerImageMimeType` VARCHAR(100) NULL,
  `bannerImageFileName` VARCHAR(255) NULL,
  `stepTitle` VARCHAR(255) NOT NULL DEFAULT 'Choose your products',
  `stepDescription` TEXT NULL,
  `productItems` INTEGER NOT NULL DEFAULT 3,
  `buttonLabel` VARCHAR(100) NOT NULL DEFAULT 'Add bundle to cart',
  `bundlePriceType` VARCHAR(10) NOT NULL DEFAULT 'dynamic',
  `discountMode` VARCHAR(30) NOT NULL DEFAULT 'fixed_amount',
  `discountType` VARCHAR(30) NOT NULL DEFAULT 'fixed',
  `discountValue` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `buyQuantity` INTEGER NOT NULL DEFAULT 1,
  `getQuantity` INTEGER NOT NULL DEFAULT 1,
  `selectedGiftProductIdsJson` LONGTEXT NULL,
  `productConfiguration` VARCHAR(40) NOT NULL DEFAULT 'whole_store',
  `selectedProductIdsJson` LONGTEXT NULL,
  `selectedCollectionIdsJson` LONGTEXT NULL,
  `scheduleType` VARCHAR(20) NOT NULL DEFAULT 'immediately',
  `startDate` VARCHAR(10) NULL,
  `startTime` VARCHAR(5) NULL,
  `hasEndDate` BOOLEAN NOT NULL DEFAULT false,
  `endDate` VARCHAR(10) NULL,
  `endTime` VARCHAR(5) NULL,
  `eligibilityJson` LONGTEXT NULL,
  `customerTags` TEXT NULL,
  `customers` TEXT NULL,
  `createQuantityPackProduct` BOOLEAN NOT NULL DEFAULT false,
  `hideOutOfStockProducts` BOOLEAN NOT NULL DEFAULT false,
  `showProductSearch` BOOLEAN NOT NULL DEFAULT false,
  `hideBundleHeader` BOOLEAN NOT NULL DEFAULT false,
  `hideBannerImage` BOOLEAN NOT NULL DEFAULT false,
  `hideProductInfoModal` BOOLEAN NOT NULL DEFAULT false,
  `productImageAutoHeight` BOOLEAN NOT NULL DEFAULT false,
  `displayCompareAtPrice` BOOLEAN NOT NULL DEFAULT false,
  `redirectToCheckout` BOOLEAN NOT NULL DEFAULT false,
  `redirectToCart` BOOLEAN NOT NULL DEFAULT false,
  `backgroundColor` VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
  `cardBorderColor` VARCHAR(20) NOT NULL DEFAULT '#F2F2F2',
  `imageHeight` INTEGER NOT NULL DEFAULT 200,
  `imageHeightMobile` INTEGER NOT NULL DEFAULT 160,
  `imageDisplay` VARCHAR(30) NOT NULL DEFAULT 'Desktop/Mobile',
  `productCardDesktopSize` VARCHAR(20) NOT NULL DEFAULT 'Large',
  `productCardMobileSize` VARCHAR(20) NOT NULL DEFAULT 'Medium',
  `borderWidth` INTEGER NOT NULL DEFAULT 0,
  `borderRadius` INTEGER NOT NULL DEFAULT 0,
  `titleTextColor` VARCHAR(20) NOT NULL DEFAULT '#050505',
  `titleSize` INTEGER NOT NULL DEFAULT 14,
  `titleStyle` VARCHAR(20) NOT NULL DEFAULT 'Regular',
  `productPriceColor` VARCHAR(20) NOT NULL DEFAULT '#000000',
  `productPriceSize` INTEGER NOT NULL DEFAULT 14,
  `productPriceStyle` VARCHAR(20) NOT NULL DEFAULT 'Medium',
  `compareAtPriceColor` VARCHAR(20) NOT NULL DEFAULT '#9D9D9D',
  `compareAtPriceSize` INTEGER NOT NULL DEFAULT 12,
  `compareAtPriceStyle` VARCHAR(20) NOT NULL DEFAULT 'Light',
  `ctaBackgroundColor` VARCHAR(20) NOT NULL DEFAULT '#303030',
  `ctaTextColor` VARCHAR(20) NOT NULL DEFAULT '#F5F5F5',
  `ctaSize` INTEGER NOT NULL DEFAULT 14,
  `ctaStyle` VARCHAR(20) NOT NULL DEFAULT 'Bold',
  `variantSelectorColor` VARCHAR(20) NOT NULL DEFAULT '#383838',
  `variantSelectorSize` INTEGER NOT NULL DEFAULT 12,
  `variantSelectorStyle` VARCHAR(20) NOT NULL DEFAULT 'Regular',
  `imagePopupBackgroundColor` VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
  `imagePopupTextColor` VARCHAR(20) NOT NULL DEFAULT '#303030',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `multiple_box_page_boxId_key` (`boxId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `multiple_box_page_boxId_fkey`
    FOREIGN KEY (`boxId`) REFERENCES `combo_box` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `multiple_box_quantity_pack` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `multipleBoxPageId` INTEGER NOT NULL,
  `packKey` VARCHAR(100) NOT NULL,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `title` VARCHAR(100) NOT NULL,
  `stepTitle` VARCHAR(255) NOT NULL DEFAULT 'Choose your products',
  `stepDescription` TEXT NULL,
  `productItems` INTEGER NOT NULL DEFAULT 3,
  `buttonLabel` VARCHAR(100) NOT NULL DEFAULT 'Add bundle to cart',
  `bundlePriceType` VARCHAR(10) NOT NULL DEFAULT 'dynamic',
  `discountMode` VARCHAR(30) NOT NULL DEFAULT 'fixed_amount',
  `discountType` VARCHAR(30) NOT NULL DEFAULT 'fixed',
  `discountValue` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `buyQuantity` INTEGER NOT NULL DEFAULT 1,
  `getQuantity` INTEGER NOT NULL DEFAULT 1,
  `selectedGiftProductIdsJson` LONGTEXT NULL,
  `productConfiguration` VARCHAR(40) NOT NULL DEFAULT 'whole_store',
  `selectedProductIdsJson` LONGTEXT NULL,
  `selectedCollectionIdsJson` LONGTEXT NULL,
  `scheduleType` VARCHAR(20) NOT NULL DEFAULT 'immediately',
  `startDate` VARCHAR(10) NULL,
  `startTime` VARCHAR(5) NULL,
  `hasEndDate` BOOLEAN NOT NULL DEFAULT false,
  `endDate` VARCHAR(10) NULL,
  `endTime` VARCHAR(5) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `multiple_box_quantity_pack_multipleBoxPageId_packKey_key` (`multipleBoxPageId`, `packKey`),
  INDEX `multiple_box_quantity_pack_multipleBoxPageId_idx` (`multipleBoxPageId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `multiple_box_quantity_pack_multipleBoxPageId_fkey`
    FOREIGN KEY (`multipleBoxPageId`) REFERENCES `multiple_box_page` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
